### ISSUE TITLE
Define which scripts should ALWAYS be part of the package.json?

### ISSUE THREAD

**Issue by n8io** [utopias/hello-world#11]
For example:
- start
  - Should always be the entry point into the service/application.
  - Should never be an explicit path
  - Should always leverage $npm_package_main env variable
  - E.g., `node $npm_package_main`
- test
  - Should wrap all tests into a single script
  - E.g., `npm run test-unit && npm run test-integration && npm run test-e2e`
- lint
  - Should run all of the linting (gulp/grunt linter tasks)
- pre-commit
  - Must run and pass linting checks
- pre-push
  - Must run and pass unit tests
- clean
  - Should remove any files that are generated via npm or build processes (node_modules, bower_components, npm-debug.log, etc)
  - Should return the local project to the original "git clone" state

**Comment by jpero09** [comment]
Nice references:
- https://registry.npmjs.org/npm/latest
- https://registry.npmjs.org/jade/latest
- https://registry.npmjs.org/request/latest
